name: Test Model

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Train model for testing
      run: |
        python src/train.py
    
    - name: Run tests
      run: |
        python -m pytest tests/ -v
    
    - name: Test API
      run: |
        python app.py &
        sleep 10
        curl -X GET http://localhost:5000/health
        curl -X POST http://localhost:5000/predict \
          -H "Content-Type: application/json" \
          -d '{"features": [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]}'