name: Deploy Model

on:
  workflow_run:
    workflows: ["Train Model"]
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Build Docker image
      run: |
        docker build -t mlops-model:latest .
    
    - name: Test Docker container
      run: |
        docker run -d -p 5000:5000 --name test-container mlops-model:latest
        sleep 15
        curl -X GET http://localhost:5000/health
        docker stop test-container
        docker rm test-container
    
    # Exemple de déploiement sur une registry Docker
    - name: Login to DockerHub
      if: github.ref == 'refs/heads/main'
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Push to DockerHub
      if: github.ref == 'refs/heads/main'
      run: |
        docker tag mlops-model:latest ${{ secrets.DOCKER_USERNAME }}/mlops-model:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/mlops-model:latest