name: Train Model

on:
  push:
    branches: [ main ]
    paths: 
      - 'src/**'
      - 'requirements.txt'
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Train model
      run: |
        python src/train.py
    
    - name: Upload model artifacts
      uses: actions/upload-artifact@v4
      with:
        name: trained-model
        path: |
          models/model.pkl
          models/metrics.pkl
        retention-days: 30
    
    - name: Commit and push model
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add models/
        git diff --staged --quiet || git commit -m "Update trained model [skip ci]"
        git push